FROM python:3.7

WORKDIR /app

ADD . /app

RUN pip install -r requirements.txt

ARG EMAIL_ADDRESS
ARG EMAIL_PASSWORD
ARG EMAIL_SMTP_PORT="587"
ARG EMAIL_SMTP_SERVER="smtp.gmail.com"
ARG OCI_FINGERPRINT
ARG OCI_KEY_FILE_PATH="./private_key.pem"
ARG OCI_REGION
ARG OCI_TENANCY
ARG OCI_USER
ARG REQUEST_JSON_PATH="./request.json"
ARG WAIT_TIME="120"

ENV EMAIL_ADDRESS=${EMAIL_ADDRESS}
ENV EMAIL_PASSWORD=${EMAIL_PASSWORD}
ENV EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
ENV EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
ENV OCI_FINGERPRINT=${OCI_FINGERPRINT}
ENV OCI_REGION=${OCI_REGION}
ENV OCI_TENANCY=${OCI_TENANCY}
ENV OCI_USER=${OCI_USER}
ENV WAIT_TIME=${WAIT_TIME}

COPY "./main.py" /app/main.py
COPY "./requirements.txt" /app/requirements.txt
COPY ${OCI_KEY_FILE_PATH} /app/private_key.pem
COPY ${REQUEST_JSON_PATH} /app/request.json

CMD ["python", "main.py"]
